name: documentation

on: [push]

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger external build
        id: website
        run: |
          curl -X POST \
          -u "${{ secrets.GIT_CREDENTIALS }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/bandantonio/showdownjs.github.io/dispatches \
          --data '{"ref": "main" }'