name: documentation

on: [push]

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger external build
        env:
          token: ${{ secrets.EXT_DOCS_BUILD }}
          event: build_docs
          owner: bandantonio
          repo: showdownjs.github.io
        run: |
          curl -X POST \
          -H "Authorization: token ${token}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${owner}/${repo}/dispatches \
          -d `{ "event_type": ${event}, "client_payload": { "source": "showdown" } }`