name: documentation

on: [push]

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build documentation
        id: build_docs
        run: docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build
      
      - name: Deploy to GitHub Pages 
        if: steps.build_docs.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}