name: documentation

on:
  push:
    branches:    
      - master
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger external build
        env:
          TOKEN: ${{ secrets.DOCS_DEPLOY_KEY }}
          COMMIT: ${{ github.event.head_commit.id }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMITTER: ${{ github.event.head_commit.author.username }}
          OWNER: bandantonio
          REPO: showdownjs.github.io
        run: |
          curl -X POST \
          -H "Authorization: token ${TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
          -d '{ "event_type": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. Qu", "client_payload": { "build_message": "1Lorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. QuiLorem ipsum dolor sit, amet consectetur adipisicing elit. Hic eum quo enim quam nulla nemo unde. Qui" }'